fix: test example
graph4ai/graph4nlp pull request #502
Opened 2022-02-18 11:44 UTC by WuXuan374

## Description
- related to issue #500 
- suggested @hugochan as reviewer

## Descriptions
- bug fix in an example inside test/

2022-02-27 17:17 UTC, hugochan commented
@WuXuan374 thanks for contributing to the Graph4NLP library! I got the error `ModuleNotFoundError: No module named 'graph4nlp.pytorch.modules.graph_construction.embedding_construction` when running ` python -m graph4nlp.pytorch.test.graph_construction.run_batch_graph_embedding_construction`. It seems you also need to update the import path. Can you please take a look and fix this? Thanks!

2022-02-27 17:18 UTC, hugochan requested changes
@WuXuan374 thanks for contributing to the Graph4NLP library! I got the error ModuleNotFoundError: No module named 'graph4nlp.pytorch.modules.graph_construction.embedding_construction when running python -m graph4nlp.pytorch.test.graph_construction.run_batch_graph_embedding_construction. It seems you also need to update the import path. Can you please take a look and fix this? Thanks!

2022-02-28 01:34 UTC, WuXuan374 commented
@hugochan thanks for your reply. Here's the description for my second commit:

1.  fix import path. 
2. I mock a vocab_util.py with only 2 modifications compare to '...modules.utils.vocab_utils' (You can easily search them with comment "Modification"). The reason is in our test example, 'str' has no extract() method specified (which would be defined in a class like Text2TextDataItem), so I just replace instance.extract() with instance.split() as a workaround. A better solution would be to define a DataItem object with relevant extract() method for 'str'.
3. I cannot fix L75, so I commented out L71-L79.
4. I add some print() statements (commented out in the file)
5. For me, this test file is useful because it shows how to build graph based on texts.

2022-03-04 16:29 UTC, hugochan commented
> @hugochan thanks for your reply. Here's the description for my second commit:
> 
> 1. fix import path.
> 2. I mock a vocab_util.py with only 2 modifications compare to '...modules.utils.vocab_utils' (You can easily search them with comment "Modification"). The reason is in our test example, 'str' has no extract() method specified (which would be defined in a class like Text2TextDataItem), so I just replace instance.extract() with instance.split() as a workaround. A better solution would be to define a DataItem object with relevant extract() method for 'str'.
> 3. I cannot fix L75, so I commented out L71-L79.
> 4. I add some print() statements (commented out in the file)
> 5. For me, this test file is useful because it shows how to build graph based on texts.

@WuXuan374 Thanks again for working on making our testing better! A few comments regarding the new changes:
2) I agreed that "A better solution would be to define a DataItem object with relevant extract() method for 'str'" so that we can directly call the built-in VocabModel. Can you please take this way?
3) Regarding L75, can you take a look into this [example](https://github.com/graph4ai/graph4nlp/blob/master/examples/pytorch/text_classification/run_text_classifier.py#L58) for reference?

Thanks for your time and contribution!

2022-03-05 02:40 UTC, WuXuan374 commented
@hugochan yes I will finish 2) and 3) in a few days.

2022-03-12 10:50 UTC, WuXuan374 commented
@hugochan Hi, I've fixed the above two problems in the newest commit.

2022-03-13 15:00 UTC, hugochan commented on graph4nlp/pytorch/test/graph_construction/run_batch_graph_embedding_construction.py
> +        return self.input_text.lower().split()
@WuXuan374 `lower_case` is not used in `extract` method.

2022-03-13 15:01 UTC, hugochan commented on graph4nlp/pytorch/test/graph_construction/run_batch_graph_embedding_construction.py
> +from ...modules.graph_embedding_initialization.embedding_construction import EmbeddingConstruction
@WuXuan374 Unused import path `EmbeddingConstruction`, please remove it.

2022-03-13 15:04 UTC, hugochan commented on graph4nlp/pytorch/test/graph_construction/run_batch_graph_embedding_construction.py
> +            # print('tokens: {}'.format(tokens))
@WuXuan374 can you remove L70~L74 comments?

2022-03-13 15:05 UTC, hugochan commented on graph4nlp/pytorch/test/graph_construction/run_batch_graph_embedding_construction.py
> +        # print('after padding, token_id: {} {}'.format(tmp_token_idx.shape, tmp_token_idx))
@WuXuan374 can you remove this comment as well?

2022-03-13 15:10 UTC, hugochan commented on graph4nlp/pytorch/test/graph_construction/run_batch_graph_embedding_construction.py
>  import numpy as np
@WuXuan374 can you remove unused import `dgl`?

2022-03-13 15:15 UTC, hugochan requested changes
@WuXuan374 Looks great to me! Thank you for your contribution! Just left a few comments. You might also want to address the following lint warnings:
```
./graph4nlp/pytorch/test/graph_construction/run_batch_graph_embedding_construction.py:11:101: E501 line too long (113 > 100 characters)
./graph4nlp/pytorch/test/graph_construction/run_batch_graph_embedding_construction.py:20:1: W293 blank line contains whitespace
./graph4nlp/pytorch/test/graph_construction/run_batch_graph_embedding_construction.py:24:1: E305 expected 2 blank lines after class or function definition, found 1
./graph4nlp/pytorch/test/graph_construction/run_batch_graph_embedding_construction.py:44:1: W293 blank line contains whitespace
./graph4nlp/pytorch/test/graph_construction/run_batch_graph_embedding_construction.py:91:1: W293 blank line contains whitespace
```

You can find the above lint warnings by running ` ./dev/ci_lint.sh`.

2022-03-14 13:16 UTC, WuXuan374 commented
@hugochan fix lint warnings and above issues in newest commit

2022-03-17 03:27 UTC, merged

2022-03-17 03:28 UTC, hugochan commented
@WuXuan374 LGTM. Thanks for your contribution!